language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g
- tlmgr update --all --self
- tlmgr install ctex ms ulem xecjk environ trimspaces zhnumber fandol xltxtra realscripts

script:
- Rscript -e 'bookdown::render_book("index.Rmd");rmarkdown::render(input = "latex/bookdown-rticles-zh.Rmd")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
