language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 1.17.2

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd");bookdown::render_book(input = 'index.Rmd',output_format = 'bookdown::pdf_book',output_dir = '_book')'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
