language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm
  - $HOME/texlive
  - $HOME/.fonts

pandoc_version: 2.1.3

addons:
  apt:
    packages:
      - ghostscript

before_install:
  - cp -r WinFonts/* $HOME/.fonts/
  - fc-cache -v -f
  - npm install netlify-cli -g
  - tlmgr update --all --self
  - tlmgr install $(cat TeXLive.Pkgs | tr '\n' ' ') || true

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
