language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 1.17.2

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: script
  script: netlify deploy -s 9527253e-e8f4-4813-8c92-98d2b07dfd6c
  skip_cleanup: true
