language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 1.17.2

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

script:
- Rscript -e 'library(tinytex);tinytex::install_tinytex(TRUE);bookdown::render_book("index.Rmd",output_format ="bookdown::gitbook");bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book");bookdown::render_book("index.Rmd", output_format = "bookdown::epub_book")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
