--- 
title: "Spatial Generalized Linear Mixed Models and its Applications"
subtitle: "master thesis template"
institute: "China University of Mining and Technology, Beijing"
author: "Xiangyun Huang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: ctexbook
mainfont: Nimbus Roman No9 L
monofont: Nimbus Mono L
sansfont: Nimbus Sans L
geometry: [tmargin=3.0cm, bmargin=3.0cm, lmargin=3.0cm, rmargin=3.0cm]
classoption: "hyperref, a4paper, UTF8, zihao = -4, linespread = 1.3"
bibliography: [refer.bib,packages.bib]
natbiboptions: super,square
biblio-style: natbib
link-citations: yes
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.showtext = TRUE,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)
library(ggplot2)
theme_set(theme_minimal())
```

\mainmatter

# 符号说明

符号   | 含义             | 符号  | 含义
 :----------: |   :-------------------:   | :----------: |  :-------------------: 
$\mathbf{A}$               | 粗体            | $\Omega$                   | 全集
$\mathit{A}$               | 集合 文本斜体   | $\mathbb{R,C}$             | 实（复）数集
$\mathtt{A}$               | 文本等宽体      | $\mathrm{A}$               | 文本罗马体
$\mathcal{A}$              | 集族            | $\varnothing$              | 空集
$\mathsf{A}$               | 矩阵 文本等线体  | $\mathsf{A}^{-}$           | 矩阵的广义逆
$\mathsf{A}^\top$          | 矩阵转置        | $\bar{x}$                   | 平均值
$\mathsf{A}^{-1}$          | 矩阵的逆        | $\vert a \vert$             | 标量绝对值
$\mathsf{A}^{\star}$       | 伴随矩阵        | $\mathop{\mathrm{diag}}(\mathsf{A})$ | 矩阵的对角
$\lVert \mathsf{A} \rVert_{1}$       | 矩阵的1范数     | $\mathsf{I}$                | 单位矩阵
$\lVert \mathsf{A} \rVert_{2}$       | 矩阵的2范数     | $\mathsf{I}_{n}$            | $n$ 阶单位矩阵
$\lVert \mathsf{A} \rVert_{\infty}$  | 矩阵的无穷范数  | $\mathsf{1}$                | 全1矩阵
$\lVert \mathsf{X} \rVert_{1}$       | 向量的1范数     | $\mathsf{1}_{n}$            | $n$ 阶全1矩阵
$\lVert \mathsf{X} \rVert_{2}$       | 向量的2范数     | $\lVert \mathsf{X} \rVert_{\infty}$  | 向量的无穷范数
$\langle\mathsf{X},\mathsf{Y}\rangle$ | 向量的内积    | $f(\mathsf{X})$        | 随机变量的函数
$\mathsf{X} \wedge \mathsf{Y}$       | 向量的外积     | $\nabla{\mathsf{X}}$   | 向量微分或梯度
$\beta$                              | 模型系数             | $\theta$               | 模型或分布参数
$\alpha$                             | 模型截距             | $\Theta$               | 参数空间
$\hat{\beta}_{ls}$                   | LS估计     | $f(x)$                 | 标量值函数
$\hat{\beta}_{mle}$                  | MLE估计    | $f(\mathsf{X})$        | 向量的函数
$\hat{\beta}_{bayes}$                | Bayes估计  | $\mathcal{X}$          | 概率空间
$\rho$                              | 相关系数            | $\kappa$      | 贝塞尔函数的阶
$\phi$                              | 尺度参数            | $u$           | 距离 $\lVert \mathsf{x}_1 -\mathsf{x}_2 \rVert$
$\mathbb{R}^2$                      | 二维实数域        | $S(x)$        | 空间过程
$\mathcal{S}$      | $\mathcal{S} = \{S(x):x \in \mathbb{R}^2\}$ | $\mathcal{S}^{\star}$  | 随机过程 $\mathcal{S}$ 的近似

- 多元统计分析 高惠璇 矩阵符号表示
- 深度学习符号表示 <https://github.com/XiangyunHuang/dlbook>

举例，线性模型的表示，此处 $Y$ 为 $n\times 1$列向量，$X$ 为$p\times n$的矩阵，$\beta$ 为 $p\times 1$的列向量 ，$\epsilon$ 为$n\times1$列向量
$$Y = X'\beta + \epsilon$$
$$\mathsf{A} = \varGamma^\top\Lambda\varGamma$$
$$\mathsf{u} = (u_1,u_2,\cdots,u_n)$$
$$\mathsf{x} = (x_1,x_2,\cdots,x_n)$$
期望 $\mathsf{E}$ 正态分布 $\mathcal{N}(\mathsf{x};\mu,\Sigma)$
对数 $\log$ 协方差 $\mathsf{Cov},\mathsf{Var}$ 

矩阵 $$\mathsf{Y} = (\mathsf{y}^{(1)},\mathsf{y}^{(n)},\cdots,\mathsf{y}^{(n)})$$
其中 $\mathsf{y}^{(i)} = (y_{1i},y_{2i},\cdots,y_{ni})$ 表示第 $i$ 列

梅隆函数(Matern function)是描述空间相关性的常用函数，它带有两参数$\kappa$ 和 $\phi$，具体形式如下：
$$\rho(u) = \big\{2^{\kappa-1}\Gamma(\kappa)\big\}^{-1}(u/\phi)^{\kappa}K_{\kappa}(u/\phi)$$
其中，$K_{\kappa}(\cdot)$ 表示 $\kappa$ 阶修正的贝塞尔函数

- 向量 `\mathsf` $\mathsf{x} = (x_1,x_2,\cdots,x_n)$ 此处 $\mathsf{x}$ 是小写
- 矩阵 `\mathbf` 矩阵的向量表示，$\mathsf{X} = (\mathsf{x}^{(1)},\mathsf{x}^{(2)},\cdots,\mathsf{x}^{(n)})$ 此处 $\mathsf{X}$ 是大写，矩阵的元素表示 $\mathsf{X} = (x_{ij})_{n\times p}$


> 先不要管符号说明，把后续模型方程写完了再说


